services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/intershop
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: intershop
      POSTGRES_PASSWORD: intershop
      POSTGRES_DB: intershop