services:
  app:
    container_name: shop-main
    build: ./shop-main
    ports:
      - "8080:8080"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/intershop
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/intershop
      - SPRING_DATASOURCE_USERNAME=intershop
      - SPRING_DATASOURCE_PASSWORD=intershop
      - PAYMENT_SERVICE_URL=http://payment-service:8081/intershop
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_TIMEOUT=PT10S
      - SPRING_LIQUIBASE_CHANGELOG=classpath:liquibase/db.changelog-master.yml
      - SPRING_LIQUIBASE_ENABLED=true
      - KEYCLOAK_CLIENT_SECRET=${CLIENT_SECRET}
      - KEYCLOAK_CLIENT_ID=intershop
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  payment-service:
    container_name: shop-payment
    build: ./shop-payment
    ports:
      - "8081:8081"
    depends_on:
      keycloak:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "intershop"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: intershop
      POSTGRES_PASSWORD: intershop
      POSTGRES_DB: intershop

  redis:
    container_name: redis
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
 
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=keycloak
    ports:
      - "8082:8080"
    command:
      - start-dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/master >/dev/null 2>&1 || exit 1"]        
      interval: 10s
      timeout: 5s
      retries: 5