services:
  app:
    build: ./shop
    ports:
      - "8080:8080"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/intershop
      - SPRING_DATASOURCE_USERNAME=intershop
      - SPRING_DATASOURCE_PASSWORD=intershop
      - PAYMENT_SERVICE_URL=http://payment-service:8081/intershop
    depends_on:
      - postgres

  payment-service:
    build: ./shop-payment
    ports:
      - "8081:8081"
    depends_on:
      - redis

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: intershop
      POSTGRES_PASSWORD: intershop
      POSTGRES_DB: intershop

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
