services:
  db:
    image: postgres:latest
    container_name: intershop-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: intershop
      POSTGRES_PASSWORD: intershop
      POSTGRES_DB: intershop

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=keycloak
    ports:
      - "8082:8080"
    command:
      - start-dev