# Общие настройки, применяемые ко всем профилям
server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      springframework: INFO

spring:
  main:
    banner-mode: off
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    r2dbc:
      repositories:
        enabled: true

  r2dbc:
    url: r2dbc:postgresql://localhost:${testcontainers.postgresql.port}/testdb
    username: testuser
    password: testpass

  datasource:
    url: jdbc:postgresql://your-postgresql-host:5432/yourdb
    username: your-username
    password: your-password
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

# Настройки для Testcontainers
testcontainers:
  postgresql:
    port: 5432
    database: testdb
    username: testuser
    password: testpass
