# -Dspring.profiles.active=dev
server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      springframework:
        r2dbc: INFO
        web: INFO
        http: INFO
        core: INFO
      reactor:
        netty: INFO

spring:
  main:
    banner-mode: off

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  # liquibase:
  #   url: jdbc:postgresql://host.docker.internal:54332/intershop
  #   user: postgres
  #   password: postgres
  #   default-schema: shop
  #   change-log: classpath:liquibase/liquibase.changelog-master.xml
  #   driver-class-name: org.postgresql.Driver

  application.name: intershop

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop
    username: intershop
    password: intershop
    pool:
      enabled: true

  # sql:
  #   init:
  #     mode: always

  data:
    r2dbc:
      repositories:
        enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  # jpa:
  #   properties.hibernate.generate_statistics: false
  #   hibernate:
  #     ddl-auto: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


---
# Профиль mvn spring-boot:run -Dspring-boot.run.profiles=dev
spring:
  config:
    activate:
      on-profile: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop
    username: intershop
    password: intershop
    pool:
      enabled: true