server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      springframework: INFO

spring:
  main:
    banner-mode: off
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    r2dbc:
      repositories:
        enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html