server:
  port: 8080

payment:
  service:
    url: http://localhost:8081

logging:
  level:
    root: DEBUG
    org:
      springframework:
        r2dbc: INFO
        web: INFO
        http: INFO
        core: INFO
        boot:
          autoconfigure:
            liquibase: INFO
      reactor:
        netty: INFO

spring:
  main:
    banner-mode: off

  cache:
    type: redis

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  sql:
    init:
      mode: always

  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/intershop
    username: intershop
    password: intershop

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop
    username: intershop
    password: intershop
    pool:
      enabled: true

  data:
    redis:
      timeout: PT10S
      repositories:
        enabled: false
      host: localhost
      port: 6379

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  # jpa:
  #   properties.hibernate.generate_statistics: false
  #   hibernate:
  #     ddl-auto: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        # Keycloak OAuth2 Client Configuration
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8082/realms/master/protocol/openid-connect/token}
            authorization-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8082/realms/master/protocol/openid-connect/auth}
            user-info-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8082/realms/master/protocol/openid-connect/userinfo}
            jwk-set-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8082/realms/master/protocol/openid-connect/certs}
            issuer-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8082/realms/master}

        # Client Registration
        registration:
          yandex:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${KEYCLOAK_CLIENT_ID:intershop}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:HBpBcSUPAiYmJM1yPQgxynn6m9j0AEHt}
            scope: profile
            client-authentication-method: client_secret_post
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8082/realms/master}

springdoc:
  info:
    title: My API
    description: API для управления пользователями
  api-docs:
    version: OPENAPI_3_1
  swagger-ui:
    enabled: true
    path: /help.html
    try-it-out-enabled: true
    persist-authorization: true
    packages.to.scan: ru.alexgur.intershop

---
# Профиль mvn spring-boot:run -Dspring-boot.run.profiles=dev
spring:
  config:
    activate:
      on-profile: dev

  sql:
    init:
      mode: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop
    username: intershop
    password: intershop
    pool:
      enabled: true

  data:
    redis:
      timeout: PT10S
      repositories:
        enabled: false
      host: localhost
      port: 6379