name: Java CI with Maven

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # - name: Checkstyle
    #   run: mvn checkstyle:checkstyle
        
    # - name: Build and test with Maven
    #   run: |
    #     mvn clean install -B -DskipTests=false --file pom.xml
    #     mvn test --file pom.xml

    - name: Check and Build application
      run: |
        cp -rf ./tests/checkstyle.xml ./checkstyle.xml
        cp -rf ./tests/suppressions.xml ./suppressions.xml
        mvn install -P check --no-transfer-progress
        docker compose build
      
      - name: Compose down
        run: |
          docker compose down