name: Java CI with Maven

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'openjdk'
        cache: maven

    - name: Checkstyle
      run: mvn checkstyle:checkstyle
        
    - name: Build and test with Maven
      run: |
        mvn clean install -B -DskipTests=false --file pom.xml
        mvn test --file pom.xml