name: Java CI with Maven

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Checkstyle
      run: mvn checkstyle:checkstyle -q

    - name: Checkstyle (suppress detailed output)
      run: |
        # Запускаем Checkstyle и сохраняем вывод в переменную
        CHECKSTYLE_OUTPUT=$(mvn checkstyle:checkstyle 2>&1)
        # Проверяем статус выполнения
        if [[ $? -ne 0 ]]; then
          # Если есть ошибки, выводим содержимое переменной
          echo "::error::Checkstyle found issues:"
          echo "$CHECKSTYLE_OUTPUT"
          exit 1
        fi

    - name: Build and test with Maven
      run: |
        mvn clean install -B -DskipTests=false --file pom.xml
        
    - name: Build all and run
      run: |
        docker compose build
        docker compose up --detach
        
    - name: Shut down all
      run: |
        docker compose down