name: Java CI with Maven

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and test with Maven
      run: |
        mvn clean install -B -DskipTests=true --file pom.xml

    - name: Checkstyle
      run: mvn checkstyle:checkstyle
        
    # - name: Build all and run
    #   run: |
    #     docker compose build
    #     docker compose up --detach
        
    # - name: Shut down all
    #   run: |
    #     docker compose down